# Generated by Django 6.0.5 on 2026-05-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdeposit',
            name='amount_paid_on_pickup',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
