# Generated by Django 6.0.5 on 2026-05-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0004_supplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
