# Generated by Django 6.0.5 on 2026-05-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0002_customerdeposit_amount_paid_on_pickup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdeposit',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
