# Generated by Django 6.0.5 on 2026-05-25 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0005_supplier_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='NIN',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid NIN e.g. CM20100012345678 (2 letters + 14 digits)', regex='^[A-Z]{2}\\d{14}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Ugandan phone number e.g. 0712345678 or 256712345678', regex='^(\\+256|256|0)7\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='amount_deposited',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Deposit amount must be at least 1 UGX')]),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='amount_paid_on_pickup',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Amount paid on pickup cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Quantity cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Unit price must be at least 1 UGX')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Stock quantity cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Unit cost must be at least 1 UGX')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Unit price must be at least 1 UGX')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0, message='Distance cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Sale quantity must be at least 1')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Total price must be at least 1 UGX')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Unit price must be at least 1 UGX')]),
        ),
        migrations.AlterField(
            model_name='stockarrival',
            name='quantity_received',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Quantity received must be at least 1')]),
        ),
        migrations.AlterField(
            model_name='stockarrival',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Unit cost must be at least 1 UGX')]),
        ),
        migrations.AlterField(
            model_name='stockarrival',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Unit price must be at least 1 UGX')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Credit amount cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Ugandan phone number e.g. 0712345678 or 256712345678', regex='^(\\+256|256|0)7\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Quantity cannot be negative')]),
        ),
    ]
