# Generated by Django 6.0.5 on 2026-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0006_alter_customer_nin_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdeposit',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='customerdeposit',
            name='units_equivalent',
        ),
        migrations.AddField(
            model_name='customerdeposit',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='amount_deposited',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='amount_paid_on_pickup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ready_pickup', 'Ready Pickup'), ('collected', 'Collected')], default='active', max_length=20),
        ),
    ]
