# Generated by Django 6.0.5 on 2026-05-28 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0007_remove_customerdeposit_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdeposit',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='customerdeposit',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Unit price must be at least 1 UGX')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdeposit',
            name='units_equivalent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='amount_deposited',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Deposit amount must be at least 1 UGX')]),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='amount_paid_on_pickup',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Amount paid on pickup cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Quantity cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='customerdeposit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ready_pickup', 'Ready for Pickup'), ('collected', 'Collected')], default='active', max_length=20),
        ),
    ]
